---
title: "simpleRegress"
author: "Galilea Hernandez"
date: "Fall 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

## Model WEIGHT ~ NECK  this is an example  

```{r}
simp <- lm(WEIGHT~NECK,data=bears)
plot(WEIGHT~NECK,data=bears)
abline(simp)
summary.lm(simp)
```


## Compare all models that predict WEIGHT other than NECK. Then order them from worst to best by its value of Adjusted-Rsquared (bigger is better), or by RSE (residual standard error) where smaller is better. 


```{r}
agemodel <- lm(WEIGHT~AGE,data=bears)
plot(WEIGHT~AGE,data=bears)
abline(agemodel)
summary.lm(agemodel)
```
```{r}
headlenmodel <- lm(WEIGHT~HEADLEN,data=bears)
plot(WEIGHT~HEADLEN,data=bears)
abline(headlenmodel)
summary.lm(headlenmodel)
```

Best to worst:

1.NECK
2.HEADLEN
3.AGE


```{r}
headwthmodel <- lm(WEIGHT~HEADWTH,data=bears)
plot(WEIGHT~HEADWTH,data=bears)
abline(headwthmodel)
summary.lm(headwthmodel)
```








